### ISSUE TITLE
html-dialog-demos-test: Version is 94005 instead of version 100000.

### ISSUE THREAD

**Issue by phochstr** [axonivy-market/demo-projects#599]
Dear @ivy-sgi, we have found the following bug: 

** Describe the bug**
- The test project has not been updated to version 10, it is still 94005.

**To Reproduce**
1. Import HTML Dialog Demos from market into an Ivy 10.0.2, including the test project.
2. Watch out for compile errors.

** Describe the bug**
- The test project has not been updated to version 10, it is still 94005.

**To Reproduce**
1. Import HTML Dialog Demos from market into an Ivy 10.0.2, including the test project.
2. Watch out for compile errors.
![Selection_187](https://github.com/user-attachments/assets/27dc8068-1700-41e4-97ec-8a70bc1f56d4)

**Expected behavior**
No compile errors shall occur.

**Screenshots**

**Additional context**

ialog Demos. There are cases when it would be nice to know if the current version really works with my (offline) Designer.

**Expected behavior**
No compile errors shall occur.

The actual range of compatible versions of this HTML Demos Version is shown.

**Screenshots**

**Additional context**

**Comment by ivy-sgi** [comment]
Dear @phochstr Our dev team will fix it soon.

**Comment by alexsuter** [comment]
Hello @ivy-sgi 
demo-projects are maintained by ivyTeam. You don't need to fix things here.

This issue already has been fixed one year ago:
https://github.com/axonivy-market/demo-projects/blob/release/10.0/html-dialog/html-dialog-demos-test/.settings/ch.ivyteam.ivy.designer.prefs
